### ISSUE TITLE
`proxy_username` and `proxy_password` don't seem to be set

### ISSUE THREAD

**Issue by Wesselinator** [porla/porla#317]
Trying to run a socks5 proxy with auth.

Looking at the code it doesn't look like Porla is [setting](https://libtorrent.org/single-page-ref.html#settings-pack) `proxy_username` or `proxy_password` anywhere:
https://github.com/porla/porla/blob/6bbe62b6bf41ab6a636ab5638884859af257199b/src/config.cpp#L299-L326

It does look to be setup in the Settings UI
https://github.com/porla/porla/blob/6bbe62b6bf41ab6a636ab5638884859af257199b/html/src/components/settings/ProxySettingsTab.tsx#L81-L107

But then not in the schema
https://github.com/porla/porla/blob/6bbe62b6bf41ab6a636ab5638884859af257199b/html/src/components/SettingsDrawer.tsx#L19-L49

> Side note: How does one get to the settings UI?

**Comment by Wesselinator** [comment]
Is it just as simple as doing:
```c++
     if (const auto val = (*proxy_tbl)["username"].value<std::string>()) 
         cfg->sessions.at("default").set_str(lt::settings_pack::proxy_username, *val); 
  
     if (const auto val = (*proxy_tbl)["password"].value<std::string>()) 
         cfg->sessions.at("default").set_str(lt::settings_pack::proxy_password, *val); 
```

or is there a gotcha?

**Comment by vktr** [comment]
Hi! I think those tsx files are leftovers and not used - but you can set the proxy username/password (for the default session) from the config like so,

```toml
[session_settings]
proxy_username = "foo"
proxy_password = "bar"
```

Or, if you use named sessions,

```toml
[sessions.<name>.settings]
proxy_username = "foo"
proxy_password = "bar"
```

Those settings tables are just a 1:1 mapping of the libtorrent settings with some filtering on disallowed settings.

**Comment by Wesselinator** [comment]
Ah I missed something.  
Turns out LibTorrent has distinct [proxy type](https://libtorrent.org/reference-Settings.html#proxy_type_t) (`socks5_pw` : `3`) for SOCKS5 with auth.

so the correct settings for this is:
```toml
[session_settings]
proxy_type = 3
proxy_username = "foo"
proxy_password = "bar"
```

**Comment by Wesselinator** [comment]
Note, I am aware that the socks5 auth is in [cleartext](https://www.rfc-editor.org/rfc/rfc1929#section-3) and provides questionable security.  

The reason I have it running with auth is that it felt wrong to run it without, given it is an option.  
(I am running it with guardrails)

**Comment by Wesselinator** [comment]
For completeness for others you also need the other settings set too:  

#### Mixed:
```toml
[session_settings]
proxy_type = 3
proxy_username = "foo"
proxy_password = "bar"

[proxy]
host = "some.host.here"
port = 11011
hostnames = true
peer_connections = true
tracker_connections = true
```

#### With only `session_settings`:
```toml
[session_settings]
proxy_hostname = "some.host.here"
proxy_port = 11011
proxy_type = 3
proxy_hostnames = true
proxy_peer_connections = true
proxy_tracker_connections = true
proxy_username = "foo"
proxy_password = "bar"
```
