### ISSUE TITLE
Add actions

### ISSUE THREAD

**Issue by vktr** [porla/porla#51]
Porla should support some kind of dynamic actions - user-specified things that run on certain events. Adding Duktape would provide a JS engine we can use for simple actions like

```js
function init(porla) {
  porla.on("torrents:finished", function (torrent) {
    torrent.pause();
  });
}
```

This can then be configured in `porla.toml`,

```toml
[actions.pause-finished]
src = "path/to.js"
```
